apollo:
  bootstrap:
    enabled: true
    namespaces: "application,ys.sharp.config,ys.sharp.jdbc.common,ys.sharp.jdbc.master,ys.sharp.jdbc.slave_1,ys.sharp.redis"

eureka:
  client:
    serviceUrl:
      defaultZone: http://39.105.158.174:7001/eureka

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always