server:
  port: 8081
spring:
  application:
    name: ys-gateway
  cloud:
    gateway:
      routes:
        - id: neo_route
          uri: http://www.163.com
          predicates:
            - Path=/spring-cloud
        - id: neo_route1
          uri: http://localhost:8082
          predicates:
            - Path=/ddd
          filters:
            - StripPrefix= 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://39.105.158.174:7001/eureka