server:
  port: 8083

spring:
  application:
    name: ys-admin
  boot:
    admin:
      notify:
        mail:
          enabled: false #false：关闭发送邮件，true：发送邮件
          from: 15216880849@qq.com
          ignore-changes: UNKNOWN:UP,UNKNOWN:OFFLINE,OFFLINE:UP
          to: 15216880849@qq.com
  mail:
    host: smtp.qq.com
    username: 15216880849@qq.com
    password: '123123123231'
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://39.105.158.174:7001/eureka
